### ISSUE TITLE
Android Build Error after updating to latest Xamarin.Forms.Maps

### ISSUE THREAD

**Issue by walkerc4** [zauberzeug/SimpleLocation#2]
Error when trying to build after updating to latest Xamarin.Forms.Maps

 Error CS7069: Reference to type `Android.Gms.Common.IGooglePlayServicesClientOnConnectionFailedListener' claims it is defined assembly`GooglePlayServicesLib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null', but it could not be found (CS7069) (X.App.Droid)

**Comment by falkoschindler** [comment]
Unfortunately, I can't reproduce the error.

Which version of Xamarin.Forms.Maps, Xamarin.Forms and Xamarin.GooglePlayServices are you referring to?

Can you reproduce the bug using the included Demo.Droid project? That's what I'm doing: Adding the Xamarin.Forms.Maps nuget package to the Android project and rebuilding the solution.

The error seems like a version conflict between Xamarin.Forms.Maps' and SimpleStorage's GooglePlayService dependency. But the required version hasn't changed since Xamarin.Forms.Maps 1.3.2.
